### ISSUE TITLE
mistake in readme

### ISSUE THREAD

**Issue by dinuchiriac** [DoubleSpout/node-threads-a-gogo2#2]
There is a mistake in "Quick example" from README, 
module was assigned to tagg2 variable (see first line) but used as a tagg:
...var thread = tagg.create(th_func, function(err, res)...

Also i have a question about sharing variables between threads, it is possible to share them, not just to send them to thread through a buf, but to share main thread memory with other threads ?

**Comment by DoubleSpout** [comment]
thanks, i have fixed the bugs.
In javascript it can't share object reference in multi treads, because of the v8 engine.
see the v8 doc v8::isolate:
[http://izs.me/v8-docs/classv8_1_1Isolate.html](http://izs.me/v8-docs/classv8_1_1Isolate.html)
please pay  attention to the words " Objects from one isolate must not be used in other isolates.  ", so i have no idea how to share the object reference  in multi threads.
if you indeed want to share object in multi threads,using c++ addons and libuv.
